# version: '3.9'
# services:
#   db:
#     image: mysql:9.0.1
#     ports:
#       - "3306:3306"
#     restart: always
#     volumes:
#       - mysql_data:/var/lib/mysql 
#     environment:
#       - MYSQL_ROOT_PASSWORD=rootpassword
#       - MYSQL_USER=root
#       - MYSQL_PASSWORD=root
#       - MYSQL_DATABASE=personaldb
# volumes:
#   mysql_data: {}


version: '3.9'
services:
  db:
    image: mysql:9.0.1
    restart: always
    environment:
      MYSQL_DATABASE: 'personaldb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'admin1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: